### ISSUE TITLE
自動でデプロイするワークフローに publish スクリプトを入れる

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/mdn-translation-guide#11]
## issue purpose
- #10 のワークフローに publish スクリプトを入れる
- [purpose somthing](https://github.com/mozilla-japan/mdn-translation-guide/pull/10#issuecomment-1310413954)

## Close conditions
- [ ] [something....](https://github.com/mozilla-japan/mdn-translation-guide/pull/10#issuecomment-1310413954)
  - publish のスクリプトをワークフローに組み込んでマージされたら

**Comment by yoshinorin** [comment]
@gurezo 
ありがとうございます。おそらく `Settings -> Pages -> Source` で `GitHub Actions (Beta)` を選択している場合、 `gh-pages` ブランチを使用したデプロイ（publish スクリプトを用いたデプロイ）はできないのではないかと思います。

1. `GitHub Actions (Beta)` を選択している場合:
    - #3 の対応でデプロイできる
    - `gh-pages` ブランチを使用したデプロイはできない
        - （ローカルからのデプロイもできない）
2. `Deploy from Branch` を選択している場合: 
    - #3 の方法ではデプロイできない 
    - `gh-pages` ブランチを使用したデプロイはできる
        - （ローカルからデプロイできる） 

...の二者択一になると思います（すみません、検証は行っていません...）。

ですので、どちらかを選ばないといけないと思うのですが、この課題の通り `2.` の方法で対応する方向にしますか？その場合は `Settings -> Pages -> Source` の設定を `Deploy from Branch` に戻していただく必要があるかなと思います。

**Comment by gurezo** [comment]
@yoshinorin 
なるほど、そういうことなんですね。
無理に `npm run publish` は使う理由は無いので、一旦この issue は閉じますね。
